### PR TITLE
Retrieve VM IP address using libvirt

### LINKED ISSUE #8: Use libvirt DHCP leases API
Fog::Compute::Libvirt::Server#addresses [runs an external shell command](https://github.com/fog/fog-libvirt/blob/e7fa6c2409cf2e740d9e7056ea013f5914a90a13/lib/fog/libvirt/models/compute/server.rb#L311) to determine the IP address of a VM that has a given MAC address. The implementation assumes libvirtd runs on localhost or can be SSHed to; it ignores other cases, such as a TCP transport. Please use [the ruby-libvirt bindings' `dhcp_leases` method](http://libvirt.org/git/?p=ruby-libvirt.git;a=blob;f=ext/libvirt/network.c;h=7c77d730bc9d1c5b4d044873a049ed1f78560b34;hb=HEAD#l287), to also support the case when libvirtd runs on a remote host, using a TCP transport.

The code should be something along these lines:
```
libvirt_conn = @client
libvirt_network = libvirt_conn.lookup_network_by_name('default')
libvirt_network.dhcp_leases('52:54:00:54:74:88')
```

### PR DESCRIPTION
**Pull request by dcbw**
Requires ruby-libvirt 0.6.0 plus this patch:

https://www.redhat.com/archives/libvir-list/2016-January/msg00147.html

Closes #8

### CODE REVIEW

**Comment by dcbw** [comment]
I assume you want testcases too, but does this approach look OK?  How would backwards compat for ruby-libvirt < 0.6.x work?

**Comment by dcbw** [comment]
ruby-libvirt patch has been committed: http://libvirt.org/git/?p=ruby-libvirt.git;a=commit;h=c2d4192ebf28b8030b753b715a72f0cdf725d313

**Comment by dcbw** [comment]
@strzibny any thoughts on this patch?  The CI errors don't seem to be related to the patch as they happen for me without it too.

**Comment by dcbw** [comment]
Repush to see if tests work now... bundle install (which the test is doing) works for me locally on F23.

**Comment by plribeiro3000** [comment]
Which ruby version are you using in your own machine?

**Comment by dcbw** [comment]
@plribeiro3000 ruby 2.2.4 (on Fedora 23)

**Comment by plribeiro3000** [comment]
@dcbw Could you add some tests around this?

Thanks.

**Comment by dcbw** [comment]
@plribeiro3000 sure, will do.

**Comment by plribeiro3000** [comment]
Awesome. Thanks!

**Comment by dcbw** [comment]
@plribeiro3000 PTAL, thanks!

**Comment by plribeiro3000** [comment]
Thanks!

**Comment by fduminy** [comment]
Is that integrated in libvirt-java ?
I can't find any update since almost one year on redhat/github repositories.
Who is/are the maintainer(s) ?

**Comment by plribeiro3000** [comment]
@fduminy Dunno about the `libvirt-java` project.
Don't even know where is the repo. Maybe you should open a ticket there?

**Pull request merged**
