### PR TITLE
fix error raising for cloud-init genisoimage

### PR DESCRIPTION
**Pull request by mmoll**
Also adjust the error message so it's easier to find the cause. I didn't have genisoimage installed on the host in question...

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Thanks @mmoll .

Could you use the standard format instead?

```ruby
raise Fog::Errors::Error, "Couldn't generate cloud-init iso disk with genisoimage."
```

**Comment by mmoll** [comment]
@plribeiro3000 I can do that, but a quick "git grep" over fog-libvirt shows zero occourences of that format, maybe the others should get changed then, too?

**Comment by plribeiro3000** [comment]
Hmm. Yeah, they can be changed but we can leave this to another PR then.

👍

**Comment by plribeiro3000** [comment]
Thanks for your patience. =)

**Pull request merged**
